### ISSUE TITLE
Stepsize checking for monthly files

### ISSUE THREAD

**Issue by philipjdavis** [metosfc/ncdfchecker#10]
Currently, the script assumes a fixed time interval, and thus cannot handle monthly files where the data time step will be different from month to month, and will also depend on the the model initialisation date and run duration. 

Additionally, the documentation should be updated to:
* Describe how required_intervals is handled for monthly files,
* As a bonus, we need to include documentation about the allowed_dimensions data structure.

**Comment by arjclark** [comment]
Closed by #11
